def parse_nuts(nuts_key):
	nuts_dict = (
		{"nuts_kod": "CZ", "nazev": "ČR", "nuts_parent": "ČR", "nuts_type": "NUTS2_oblast", "nuts_coment": ""},
		{"nuts_kod": "CZ0", "nazev": "ČR", "nuts_parent": "ČR", "nuts_type": "NUTS2_oblast", "nuts_coment": ""},
		{"nuts_kod": "CZ01", "nazev": "Praha", "nuts_parent": "ČR", "nuts_type": "NUTS2_oblast", "nuts_coment": ""},
		{"nuts_kod": "CZ010", "nazev": "Hlavní město Praha", "nuts_parent": "Praha", "nuts_type": "NUTS3_kraj", "nuts_coment": "duplikát"},
		{"nuts_kod": "CZ011", "nazev": "Hlavní město Praha", "nuts_parent": "Praha", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0111", "nazev": "Praha 1", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0112", "nazev": "Praha 2", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0113", "nazev": "Praha 3", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0114", "nazev": "Praha 4", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0115", "nazev": "Praha 5", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0116", "nazev": "Praha 6", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0117", "nazev": "Praha 7", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0118", "nazev": "Praha 8", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0119", "nazev": "Praha 9", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ011A", "nazev": "Praha 10", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ011B", "nazev": "Praha 11", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ011C", "nazev": "Praha 12", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ011D", "nazev": "Praha 13", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ011E", "nazev": "Praha 14", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ011F", "nazev": "Praha 15", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ011F", "nazev": "Praha 16", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": "duplikát"},
		{"nuts_kod": "CZ011F", "nazev": "Praha 17", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": "duplikát"},
		{"nuts_kod": "CZ011F", "nazev": "Praha 18", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": "duplikát"},
		{"nuts_kod": "CZ011F", "nazev": "Praha 19", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": "duplikát"},
		{"nuts_kod": "CZ011F", "nazev": "Praha 20", "nuts_parent": "Hlavní město Praha", "nuts_type": "NUTS4_okres", "nuts_coment": "duplikát"},
		{"nuts_kod": "CZ02", "nazev": "Střední Čechy", "nuts_parent": "ČR", "nuts_type": "NUTS2_oblast", "nuts_coment": ""},
		{"nuts_kod": "CZ020", "nazev": "Středočeský kraj", "nuts_parent": "Střední Čechy", "nuts_type": "NUTS3_kraj", "nuts_coment": "duplikát"},
		{"nuts_kod": "CZ021", "nazev": "Středočeský kraj", "nuts_parent": "Střední Čechy", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0211", "nazev": "Benešov", "nuts_parent": "Středočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0212", "nazev": "Beroun", "nuts_parent": "Středočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0213", "nazev": "Kladno", "nuts_parent": "Středočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0214", "nazev": "Kolín", "nuts_parent": "Středočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0215", "nazev": "Kutná Hora", "nuts_parent": "Středočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0216", "nazev": "Mělník", "nuts_parent": "Středočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0217", "nazev": "Mladá Boleslav", "nuts_parent": "Středočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0218", "nazev": "Nymburk", "nuts_parent": "Středočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0219", "nazev": "Praha-východ", "nuts_parent": "Středočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ021A", "nazev": "Praha-západ", "nuts_parent": "Středočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ021B", "nazev": "Příbram", "nuts_parent": "Středočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ021C", "nazev": "Rakovník", "nuts_parent": "Středočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ03", "nazev": "Jihozápad", "nuts_parent": "ČR", "nuts_type": "NUTS2_oblast", "nuts_coment": ""},
		{"nuts_kod": "CZ031", "nazev": "Jihočeský kraj", "nuts_parent": "Jihozápad", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0311", "nazev": "České Budějovice", "nuts_parent": "Jihočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0312", "nazev": "Český Krumlov", "nuts_parent": "Jihočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0313", "nazev": "Jindřichův Hradec", "nuts_parent": "Jihočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0314", "nazev": "Písek", "nuts_parent": "Jihočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0315", "nazev": "Prachatice", "nuts_parent": "Jihočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0316", "nazev": "Strakonice", "nuts_parent": "Jihočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0317", "nazev": "Tábor", "nuts_parent": "Jihočeský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ032", "nazev": "Plzeňský kraj", "nuts_parent": "Jihozápad", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0321", "nazev": "Domažlice", "nuts_parent": "Plzeňský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0322", "nazev": "Klatovy", "nuts_parent": "Plzeňský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0323", "nazev": "Plzeň-město", "nuts_parent": "Plzeňský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0324", "nazev": "Plzeň-jih", "nuts_parent": "Plzeňský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0325", "nazev": "Plzeň-sever", "nuts_parent": "Plzeňský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0324", "nazev": "Plzeň", "nuts_parent": "Plzeňský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": "duplikát"},
		{"nuts_kod": "CZ0326", "nazev": "Rokycany", "nuts_parent": "Plzeňský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0327", "nazev": "Tachov", "nuts_parent": "Plzeňský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ04", "nazev": "Severozápad", "nuts_parent": "ČR", "nuts_type": "NUTS2_oblast", "nuts_coment": ""},
		{"nuts_kod": "CZ041", "nazev": "Karlovarský kraj", "nuts_parent": "Severozápad", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0411", "nazev": "Cheb", "nuts_parent": "Karlovarský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0412", "nazev": "Karlovy Vary", "nuts_parent": "Karlovarský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0413", "nazev": "Sokolov", "nuts_parent": "Karlovarský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ042", "nazev": "Ústecký kraj", "nuts_parent": "Severozápad", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0421", "nazev": "Děčín", "nuts_parent": "Ústecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0422", "nazev": "Chomutov", "nuts_parent": "Ústecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0423", "nazev": "Litoměřice", "nuts_parent": "Ústecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0424", "nazev": "Louny", "nuts_parent": "Ústecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0425", "nazev": "Most", "nuts_parent": "Ústecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0426", "nazev": "Teplice", "nuts_parent": "Ústecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0427", "nazev": "Ústí nad Labem", "nuts_parent": "Ústecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ05", "nazev": "Severovýchod", "nuts_parent": "ČR", "nuts_type": "NUTS2_oblast", "nuts_coment": ""},
		{"nuts_kod": "CZ051", "nazev": "Liberecký kraj", "nuts_parent": "Severovýchod", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0511", "nazev": "Česká Lípa", "nuts_parent": "Liberecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0512", "nazev": "Jablonec nad Nisou", "nuts_parent": "Liberecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0513", "nazev": "Liberec", "nuts_parent": "Liberecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0514", "nazev": "Semily", "nuts_parent": "Liberecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ052", "nazev": "Královéhradecký kraj", "nuts_parent": "Severovýchod", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0521", "nazev": "Hradec Králové", "nuts_parent": "Královéhradecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0522", "nazev": "Jičín", "nuts_parent": "Královéhradecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0523", "nazev": "Náchod", "nuts_parent": "Královéhradecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0524", "nazev": "Rychnov nad Kněžnou", "nuts_parent": "Královéhradecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0525", "nazev": "Trutnov", "nuts_parent": "Královéhradecký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ053", "nazev": "Pardubický kraj", "nuts_parent": "Severovýchod", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0531", "nazev": "Chrudim", "nuts_parent": "Pardubický kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0532", "nazev": "Pardubice", "nuts_parent": "Pardubický kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0533", "nazev": "Svitavy", "nuts_parent": "Pardubický kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0534", "nazev": "Ústí nad Orlicí", "nuts_parent": "Pardubický kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ06", "nazev": "Pardubický kraj", "nuts_parent": "Jihovýchod", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ061", "nazev": "Vysočina", "nuts_parent": "Jihovýchod", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0611", "nazev": "Havlíčkův Brod", "nuts_parent": "Vysočina", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0612", "nazev": "Jihlava", "nuts_parent": "Vysočina", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0613", "nazev": "Pelhřimov", "nuts_parent": "Vysočina", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0614", "nazev": "Třebíč", "nuts_parent": "Vysočina", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0615", "nazev": "Žďár nad Sázavou", "nuts_parent": "Vysočina", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ062", "nazev": "Jihomoravský kraj", "nuts_parent": "Jihovýchod", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0621", "nazev": "Blansko", "nuts_parent": "Jihomoravský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0622", "nazev": "Brno-město", "nuts_parent": "Jihomoravský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0623", "nazev": "Brno-venkov", "nuts_parent": "Jihomoravský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0623", "nazev": "Brno", "nuts_parent": "Jihomoravský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": "duplikát"},
		{"nuts_kod": "CZ0624", "nazev": "Břeclav", "nuts_parent": "Jihomoravský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0625", "nazev": "Hodonín", "nuts_parent": "Jihomoravský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0626", "nazev": "Vyškov", "nuts_parent": "Jihomoravský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0627", "nazev": "Znojmo", "nuts_parent": "Jihomoravský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ063", "nazev": "Vysočina", "nuts_parent": "Jihovýchod", "nuts_type": "NUTS3_kraj", "nuts_coment": "od roku 2008"},
		{"nuts_kod": "CZ064", "nazev": "Jihomoravský kraj", "nuts_parent": "Jihovýchod", "nuts_type": "NUTS3_kraj", "nuts_coment": "od roku 2008"},
		{"nuts_kod": "CZ07", "nazev": "Střední Morava", "nuts_parent": "ČR", "nuts_type": "NUTS2_oblast", "nuts_coment": ""},
		{"nuts_kod": "CZ071", "nazev": "Olomoucký kraj", "nuts_parent": "Střední Morava", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0711", "nazev": "Jeseník", "nuts_parent": "Olomoucký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0712", "nazev": "Olomouc", "nuts_parent": "Olomoucký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0713", "nazev": "Prostějov", "nuts_parent": "Olomoucký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0714", "nazev": "Přerov", "nuts_parent": "Olomoucký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0715", "nazev": "Šumperk", "nuts_parent": "Olomoucký kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ072", "nazev": "Zlínský kraj", "nuts_parent": "Střední Morava", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0721", "nazev": "Kroměříž", "nuts_parent": "Zlínský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0722", "nazev": "Uherské Hradiště", "nuts_parent": "Zlínský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0723", "nazev": "Vsetín", "nuts_parent": "Zlínský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0724", "nazev": "Zlín", "nuts_parent": "Zlínský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ08", "nazev": "Moravskoslezsko", "nuts_parent": "ČR", "nuts_type": "NUTS2_oblast", "nuts_coment": ""},
		{"nuts_kod": "CZ080", "nazev": "Moravskoslezský kraj", "nuts_parent": "Moravskoslezsko", "nuts_type": "NUTS3_kraj", "nuts_coment": "duplikát"},
		{"nuts_kod": "CZ081", "nazev": "Moravskoslezský kraj", "nuts_parent": "Moravskoslezsko", "nuts_type": "NUTS3_kraj", "nuts_coment": ""},
		{"nuts_kod": "CZ0811", "nazev": "Bruntál", "nuts_parent": "Moravskoslezský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0812", "nazev": "Frýdek - Místek", "nuts_parent": "Moravskoslezský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0812", "nazev": "Frýdek-Místek", "nuts_parent": "Moravskoslezský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": "duplikát"},
		{"nuts_kod": "CZ0813", "nazev": "Karviná", "nuts_parent": "Moravskoslezský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0814", "nazev": "Nový Jičín", "nuts_parent": "Moravskoslezský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0814", "nazev": "Jičín", "nuts_parent": "Moravskoslezský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": "duplikát"},
		{"nuts_kod": "CZ0815", "nazev": "Opava", "nuts_parent": "Moravskoslezský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0816", "nazev": "Ostrava - město", "nuts_parent": "Moravskoslezský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": ""},
		{"nuts_kod": "CZ0816", "nazev": "Ostrava", "nuts_parent": "Moravskoslezský kraj", "nuts_type": "NUTS4_okres", "nuts_coment": "duplikát"}
		)
    
	import json
	with open("nuts.json", "w") as file:
		json.dump(nuts_dict, file, sort_keys=True, indent=4, ensure_ascii=False)

	nuts_match = {}

	for nuts_entry in nuts_dict:
		if nuts_key == nuts_entry["nuts_kod"] or nuts_key == nuts_entry["nazev"]:
			nuts_match = nuts_entry
			break

	if nuts_match.get("nuts_type", "NaN") == "NUTS3_kraj":
		nuts_match["key"] = "nazev"

	elif nuts_match.get("nuts_type", "NaN") == "NUTS4_okres":
		nuts_match["key"] = "nuts_parent"

	return nuts_match.get(nuts_match.get("key", "---"), "---").upper()

if __name__ == "__main__":
	
	print(parse_nuts("Nový Jičín").encode("utf-8"))
	print(parse_nuts("Moravskoslezský kraj").encode("utf-8"))
	print(parse_nuts("CZ0814").encode("utf-8"))
	print(parse_nuts("lesylesy").encode("utf-8"))
