# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Zakazky_II.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setWindowTitle("Zakázky II.")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("0333.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setToolTip("")
        self.centralwidget.setStatusTip("")
        self.centralwidget.setWhatsThis("")
        self.centralwidget.setAccessibleName("")
        self.centralwidget.setAccessibleDescription("")
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.headerTitle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.headerTitle.setFont(font)
        self.headerTitle.setToolTip("")
        self.headerTitle.setStatusTip("")
        self.headerTitle.setWhatsThis("")
        self.headerTitle.setAccessibleName("")
        self.headerTitle.setAccessibleDescription("")
        self.headerTitle.setText("Zakázky II.")
        self.headerTitle.setObjectName("headerTitle")
        self.horizontalLayout.addWidget(self.headerTitle)
        self.headerDate = QtWidgets.QLabel(self.centralwidget)
        self.headerDate.setSizeIncrement(QtCore.QSize(0, 2))
        self.headerDate.setToolTip("")
        self.headerDate.setStatusTip("")
        self.headerDate.setWhatsThis("")
        self.headerDate.setAccessibleName("")
        self.headerDate.setAccessibleDescription("")
        self.headerDate.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.headerDate.setText("spuštěno: 8. května 2017")
        self.headerDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.headerDate.setObjectName("headerDate")
        self.horizontalLayout.addWidget(self.headerDate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.buttonStart = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonStart.setFont(font)
        self.buttonStart.setToolTip("")
        self.buttonStart.setStatusTip("")
        self.buttonStart.setWhatsThis("")
        self.buttonStart.setAccessibleName("")
        self.buttonStart.setAccessibleDescription("")
        self.buttonStart.setText("Start")
        self.buttonStart.setAutoDefault(False)
        self.buttonStart.setDefault(True)
        self.buttonStart.setObjectName("buttonStart")
        self.verticalLayout.addWidget(self.buttonStart)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setMinimumSize(QtCore.QSize(280, 282))
        self.toolBox.setMaximumSize(QtCore.QSize(16777215, 285))
        self.toolBox.setToolTip("")
        self.toolBox.setStatusTip("")
        self.toolBox.setWhatsThis("")
        self.toolBox.setAccessibleName("")
        self.toolBox.setAccessibleDescription("")
        self.toolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setObjectName("toolBox")
        self.panelSearchFrom = QtWidgets.QWidget()
        self.panelSearchFrom.setGeometry(QtCore.QRect(0, 0, 582, 201))
        self.panelSearchFrom.setToolTip("")
        self.panelSearchFrom.setStatusTip("")
        self.panelSearchFrom.setWhatsThis("")
        self.panelSearchFrom.setAccessibleName("")
        self.panelSearchFrom.setAccessibleDescription("")
        self.panelSearchFrom.setObjectName("panelSearchFrom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.panelSearchFrom)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(165, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.calendarFrom = QtWidgets.QCalendarWidget(self.panelSearchFrom)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.calendarFrom.setPalette(palette)
        self.calendarFrom.setGridVisible(False)
        self.calendarFrom.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarFrom.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarFrom.setNavigationBarVisible(True)
        self.calendarFrom.setDateEditEnabled(True)
        self.calendarFrom.setDateEditAcceptDelay(1500)
        self.calendarFrom.setObjectName("calendarFrom")
        self.horizontalLayout_2.addWidget(self.calendarFrom)
        spacerItem1 = QtWidgets.QSpacerItem(164, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.toolBox.addItem(self.panelSearchFrom, "Vyhledávání od:")
        self.panelSearchTo = QtWidgets.QWidget()
        self.panelSearchTo.setGeometry(QtCore.QRect(0, 0, 582, 201))
        self.panelSearchTo.setObjectName("panelSearchTo")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.panelSearchTo)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(164, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.calendarTo = QtWidgets.QCalendarWidget(self.panelSearchTo)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.calendarTo.setPalette(palette)
        self.calendarTo.setGridVisible(False)
        self.calendarTo.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarTo.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarTo.setNavigationBarVisible(True)
        self.calendarTo.setDateEditEnabled(True)
        self.calendarTo.setDateEditAcceptDelay(1500)
        self.calendarTo.setObjectName("calendarTo")
        self.horizontalLayout_3.addWidget(self.calendarTo)
        spacerItem3 = QtWidgets.QSpacerItem(165, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.toolBox.addItem(self.panelSearchTo, "Vyhledávání do:")
        self.panelSearchInfo = QtWidgets.QWidget()
        self.panelSearchInfo.setGeometry(QtCore.QRect(0, 0, 582, 201))
        self.panelSearchInfo.setObjectName("panelSearchInfo")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.panelSearchInfo)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.zakazkyCount = QtWidgets.QLabel(self.panelSearchInfo)
        self.zakazkyCount.setText("Počet zakázek")
        self.zakazkyCount.setObjectName("zakazkyCount")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.zakazkyCount)
        self.zakazkyCountLcd = QtWidgets.QLCDNumber(self.panelSearchInfo)
        self.zakazkyCountLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.zakazkyCountLcd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.zakazkyCountLcd.setSmallDecimalPoint(False)
        self.zakazkyCountLcd.setDigitCount(13)
        self.zakazkyCountLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.zakazkyCountLcd.setProperty("intValue", 0)
        self.zakazkyCountLcd.setObjectName("zakazkyCountLcd")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.zakazkyCountLcd)
        self.projektovkyCount = QtWidgets.QLabel(self.panelSearchInfo)
        self.projektovkyCount.setText("Počet projektovek")
        self.projektovkyCount.setObjectName("projektovkyCount")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.projektovkyCount)
        self.projektovkyCountLcd = QtWidgets.QLCDNumber(self.panelSearchInfo)
        self.projektovkyCountLcd.setDigitCount(13)
        self.projektovkyCountLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.projektovkyCountLcd.setObjectName("projektovkyCountLcd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.projektovkyCountLcd)
        self.oldZakazazkyCount = QtWidgets.QLabel(self.panelSearchInfo)
        self.oldZakazazkyCount.setText("Počet starých zakázek")
        self.oldZakazazkyCount.setObjectName("oldZakazazkyCount")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.oldZakazazkyCount)
        self.oldZakazazkyCountLcd = QtWidgets.QLCDNumber(self.panelSearchInfo)
        self.oldZakazazkyCountLcd.setDigitCount(13)
        self.oldZakazazkyCountLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.oldZakazazkyCountLcd.setObjectName("oldZakazazkyCountLcd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.oldZakazazkyCountLcd)
        self.lineSeparator = QtWidgets.QFrame(self.panelSearchInfo)
        self.lineSeparator.setMinimumSize(QtCore.QSize(21, 1))
        self.lineSeparator.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineSeparator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineSeparator.setObjectName("lineSeparator")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.lineSeparator)
        self.zakazkaProgressBar = QtWidgets.QProgressBar(self.panelSearchInfo)
        self.zakazkaProgressBar.setProperty("value", 0)
        self.zakazkaProgressBar.setInvertedAppearance(False)
        self.zakazkaProgressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.zakazkaProgressBar.setObjectName("zakazkaProgressBar")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.zakazkaProgressBar)
        self.zakazkaProgress = QtWidgets.QLabel(self.panelSearchInfo)
        self.zakazkaProgress.setText("Aktuální zakázka")
        self.zakazkaProgress.setObjectName("zakazkaProgress")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.zakazkaProgress)
        self.zakazkyProgress = QtWidgets.QLabel(self.panelSearchInfo)
        self.zakazkyProgress.setText("Zakázky celkem")
        self.zakazkyProgress.setObjectName("zakazkyProgress")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.zakazkyProgress)
        self.zakazkyProgressBar = QtWidgets.QProgressBar(self.panelSearchInfo)
        self.zakazkyProgressBar.setProperty("value", 0)
        self.zakazkyProgressBar.setObjectName("zakazkyProgressBar")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.zakazkyProgressBar)
        self.horizontalLayout_4.addLayout(self.formLayout)
        spacerItem5 = QtWidgets.QSpacerItem(147, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.toolBox.addItem(self.panelSearchInfo, "Info")
        self.verticalLayout.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

